### ISSUE TITLE
QDKP Options

### ISSUE THREAD

**Issue by NoM0Re** [Homerocker/QDKPv2#10]
Hi, i noticed that u didn't based ur QDKP on Cataclysm version, the QDKPv2 Version: 2.7.5 (World of Warcraft: Cataclysm) has a Ingame Options Tab if u click the Icon in the Minimap rightclick.
The Version works pretty well, just the Lootframe on Bosses is not working.

Maybe u want to take this Version and modify it with ur changes to ur version would be great update.
I dont use ur QDKP because Options Tab is missin and i will not go in a txt file to change stuff and reload thats to much and very user unfriendly.

I understand if u decline that, u started this very early.

Maybe im wrong and u have a Options Tab but i never found it.

**Comment by NoM0Re** [comment]
https://www.mediafire.com/file/6ab2wwlvzu7qzxy/qdkp.zip/file

**Comment by Homerocker** [comment]
I'm not sure I will ever add this option as most guilds don't edit addon settings often anyway.
Also imo it's much easier to share guild settings with all officers as a file rather then asking them to adjust options via addon interface.
